/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import board.BoardPiece;
import board.JBoard;
import board.JBoardListener;
import controller.BoardTool;
import java.awt.Color;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.MouseEvent;

/**
 *
 * @author Fabiano
 */
public class BoardFrame extends javax.swing.JFrame implements JBoardListener,
                                                              ComponentListener {
    protected JBoard board;
    protected BoardTool boardTool;
    
    public BoardFrame() {
        initComponents();
        
        bPlayerPanel.setTextColor(Color.WHITE);
        
        board = new JBoard();
        board.addListener(this);

        boardContainerPanel.setImage("resources/bg.png");
        boardContainerPanel.add(board);
        
        this.addComponentListener(this);
        this.getContentPane().setBackground(new Color(4, 15, 4));
        this.rescaleBoard();
    }
    
    public void setControlPanelListener(ControlPanelListener l) {
        controlPanel.setListener(l);
    }
    
    private void rescaleBoard() {
        int w = boardContainerPanel.getWidth();
        int h = boardContainerPanel.getHeight();
        
        board.setSize(w, h);
        
        int bW = board.getBoardDimension().width;
        
        board.setLocation((w-bW)/2, (h-bW)/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuContainerPanel = new javax.swing.JPanel();
        wPlayerPanel = new gui.PlayerPanel();
        bPlayerPanel = new gui.PlayerPanel();
        controlPanel = new gui.ControlPanel();
        passButton = new javax.swing.JButton();
        resignButton = new javax.swing.JButton();
        countButton = new javax.swing.JButton();
        boardContainerPanel = new gui.ImagePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        wPlayerPanel.setBackground(new java.awt.Color(255, 255, 255));
        wPlayerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bPlayerPanel.setBackground(new java.awt.Color(32, 32, 32));
        bPlayerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bPlayerPanel.setForeground(new java.awt.Color(255, 255, 255));

        passButton.setText("Pass");
        passButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passButtonActionPerformed(evt);
            }
        });

        resignButton.setText("Resign");

        countButton.setText("Count");
        countButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuContainerPanelLayout = new javax.swing.GroupLayout(menuContainerPanel);
        menuContainerPanel.setLayout(menuContainerPanelLayout);
        menuContainerPanelLayout.setHorizontalGroup(
            menuContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resignButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuContainerPanelLayout.createSequentialGroup()
                        .addComponent(wPlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bPlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(countButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuContainerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        menuContainerPanelLayout.setVerticalGroup(
            menuContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bPlayerPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wPlayerPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resignButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
        );

        boardContainerPanel.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout boardContainerPanelLayout = new javax.swing.GroupLayout(boardContainerPanel);
        boardContainerPanel.setLayout(boardContainerPanelLayout);
        boardContainerPanelLayout.setHorizontalGroup(
            boardContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        boardContainerPanelLayout.setVerticalGroup(
            boardContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(boardContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boardContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passButtonActionPerformed
        boardTool = BoardTool.REMOVE_STONE;
    }//GEN-LAST:event_passButtonActionPerformed

    private void countButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countButtonActionPerformed
        int bterr = board.countTerritory(BoardPiece.BLACK_STONE);
        int wterr = board.countTerritory(BoardPiece.WHITE_STONE);
        
        board.setShowTerritory(true);
        board.repaint();
    }//GEN-LAST:event_countButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected gui.PlayerPanel bPlayerPanel;
    private gui.ImagePanel boardContainerPanel;
    protected gui.ControlPanel controlPanel;
    private javax.swing.JButton countButton;
    private javax.swing.JPanel menuContainerPanel;
    private javax.swing.JButton passButton;
    private javax.swing.JButton resignButton;
    protected gui.PlayerPanel wPlayerPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onClick(MouseEvent e, int x, int y) {
    }

    @Override
    public void componentResized(ComponentEvent e) {
        this.rescaleBoard();
    }

    @Override
    public void componentMoved(ComponentEvent e) {
        this.rescaleBoard();
    }

    @Override
    public void componentShown(ComponentEvent e) {
        //this.rescaleBoard();
    }

    @Override
    public void componentHidden(ComponentEvent e) {
    }
}
